name: Schedule Weekly Export

on:
  schedule:
    - cron: '0 0 * * 0' # Run every Sunday at midnight

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Commit and push changes
      run: |
        git config user.name 'Your GitHub Actions Bot'
        git config user.email 'kolas_skuas.0q@icloud.com'
        git add .
        git commit -m "Automated weekly export"
        git push origin main
